### PR TITLE
Add card display layout

### LINKED ISSUE #1: Create markdown structure for card display
Should be equivalent to Discord `createCardEmbed`, but English-only for now:

https://github.com/DawnbrandBots/bastion-bot/blob/master/src/card.ts#L303

All requested cards (up to a limit) should be combined in one message

### PR DESCRIPTION
**Pull request by AlphaKretin**
Closes #1 

Code is currently a sloppy draft based on the Discord version, and contains some idiosyncrasies that are no longer relevant. It's as of yet untested.

### CODE REVIEW

**Comment by AlphaKretin** [comment]
image
Besides the code cleanliness, current status is that it's too spacey, but I'm not sure how to do line breaks as opposed to paragraph breaks - Reddit ignores single newline characters.

**Comment by kevinlul** [comment]
We can use `^(superscript: content)` on the properties to reduce the space they take up, and apparently that will support single newlines. We can use bolding or a higher heading number (goes up to 6) to reduce the space taken up by headings. Finally, we can separate cards in the comment with a horizontal rule.

**Comment by kevinlul** [comment]
For image embedding, we actually have the images from Yugipedia available at `card["images"]`. We could display the first image at `card["images"][0]["image"]` the same way we embed Rush Duel card images in the Discord bot.

https://github.com/DawnbrandBots/bastion-bot/blob/50b0c7471e3ca00bb453efb4176526225f99037b/src/commands/rush-duel.ts#L450

So the URL would be `f"https://yugipedia.com/wiki/Special:Redirect/file/{card['images'][0]['image']}?utm_source=bastion"`. Careful with quotes on this.

**Comment by AlphaKretin** [comment]
Oh, I forgot Markdown could embed images (...yes, despite the fact I posted one in GitHub just there) and didn't even consider it. I'll bear that in mind. As for the rest, I'll take it into consideration for the next revision.

**Comment by kevinlul** [comment]
If we want to try for video game artworks like Discord instead of card scans, when those are available, they are found in the `illustration` field instead of `image`, and can also be guessed like with Rush Duel (`-MADU-EN-VG-artwork.png`).

https://github.com/DawnbrandBots/bastion-bot/blob/50b0c7471e3ca00bb453efb4176526225f99037b/src/commands/rush-duel.ts#L41-L46

**Comment by AlphaKretin** [comment]
I've implemented the suggested markdown changes, but single new-lines didn't work in the superscript properties block, and with double newlines it looks particularly bad either way. 
image

**Comment by AlphaKretin** [comment]
There's also the question of if we want to actually include the images, given that they'll take up further vertical space, instead of being able to tuck it in the empty corner

**Comment by kevinlul** [comment]
Okay, so `` does not work on Reddit. New Reddit has inline images, which might be UI only and not API/PRAW supported for now in comments. What we can do is simply _hyperlink_ to the image, and make it clear that the hyperlink is for the card scan or illustration. If a desktop user has Reddit Enhancement Suite, then this is expandable. If not, at least they know they can click on it to find the image. Mobile clients might render this in all sorts of ways I'm not too sure about. Even old and new Reddit do markdown differently...

**Comment by kevinlul** [comment]
I got the single-newline idea from one of the [last replies](https://www.reddit.com/r/Yugioh101/comments/dyowax/want_to_make_a_digital_bug_deck/f82yp7n/) from the bot we are trying to replace (although some of this is broken on new Reddit).

Do you have a link to the broken behaviour on new Reddit? ss

I can't find this one and all the comments I see have double newlines between superscripts.

**Comment by AlphaKretin** [comment]
[Here's the link](https://www.reddit.com/r/bastionbot/comments/12rcg0c/comment/jhmjk5i/?utm_source=share&utm_medium=web2x&context=3) to that reply
And for posterity, [here's the one](https://www.reddit.com/r/bastionbot/comments/12rcg0c/comment/jhmjpuh/?utm_source=share&utm_medium=web2x&context=3) where double new lines don't work within a superscript block.

**Comment by kevinlul** [comment]
So yeha, as discussed, you have to do `^(content)  \n^(content)` with two trailing spaces before the newline. This is effective on both old and new Reddit. I think with this, the image link, and snake casing function and variable names for pythonic style, this should be good enough for master to work off of.

**Comment by AlphaKretin** [comment]
image
The space beneath the description is a bit unfortunate, but feels unavoidable since superscript is "above" the line, followed by a header which puts a break before itself.

**Review by kevinlul — APPROVED** [review]
Thanks! I can take it from here.

**Pull request merged**
