### PR TITLE
Respond when mentioned

### LINKED ISSUE #2: Respond with general information when mentioned
- if there's no {{}}, this should be equivalent to getting pinged on Discord and mention how to use {{}}
- if there is {{}}, do card search, to permit summoning the bot outside of designated subreddits

### PR DESCRIPTION
**Pull request by kevinlul**
Closes #2 

Not tested yet since self-mentions don't work

### CODE REVIEW

**Comment by kevinlul** [comment]
image

**Comment by kevinlul** [comment]
Funny enough, that hyperlink renders on new Reddit but not old 
image

**Comment by kevinlul** [comment]
Reddit: consistent markdown parsing behaviour challenge (impossible)

image

image

**Comment by kevinlul** [comment]
Fixed

image
image

**Review by AlphaKretin — APPROVED** [review]
Code looks good and provided images prove it's tested

**Pull request merged**
